[package]
name = "cw_terra_test_mocks"
version = "0.1.0"
authors = ["0xFable"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw20 = { version = "0.8" }
cosmwasm-std = { version = "0.16" }
cw20-base = { version = "0.8", features = ["library"] } 
cw-multi-test = { version = "0.8"}
cw-storage-plus = { version = "0.8" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = "2.4.0"
schemars = "0.8.1"
lazy_static = "1.4.0"
terra-multi-test = {git="https://github.com/astroport-fi/terra-plus", rev="b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test"}
cosmwasm-bignumber = "2.2"
